[project]
name = "api"
version = "0.1.0"
description = "HTTP API for BRIDG"
dependencies = [
    "bridg",
    "common",
    "uvicorn[standard]<1.0.0,>=0.40.0",
    "pydantic<3.0.0,>=2.12.5",
    "toolz<2.0.0,>=1.0.0",
    "fastapi[standard]>=0.128.0",
]

[dependency-groups]
dev = [
    "mkinit>=1.2.0",
    "poethepoet>=0.39.0",
]
test = [
    "dirty-equals>=0.11",
    "httpx>=0.28.1",
    "polyfactory>=3.2.0",
    "syrupy>=5.0.0",
]

[build-system]
requires = ["uv_build>=0.8.12,<0.9.0"]
build-backend = "uv_build"

[tool.poe.tasks]
"api:mkinit".sequence = [
    "mkinit --recursive --relative --nomods -i api/model",
    "mkinit --recursive --relative --nomods -i tests/factory",
    "ruff check --fix",
    "ruff format"
]
"api:mkinit".default_item_type = "cmd"

[tool.ruff]
extend = "../../pyproject.toml"

[tool.ruff.lint]
ignore = ["TID252"]

[tool.uv.sources]
bridg = { workspace = true }
common = { workspace = true }
