[project]
name = "common"
version = "0.1.0"
description = "Common utilities"
dependencies = [
    "networkx[default]>=3.5",
    "python-dotenv<2.0.0,>=1.0.1",
    "pydot>=3.0.4"
]

[build-system]
requires = ["uv_build>=0.8.12,<0.9.0"]
build-backend = "uv_build"

[tool.ruff]
extend = "../../pyproject.toml"

[tool.uv.build-backend]
module-name = "bridg.common"
