name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      BRIDG_ENV: testing
      PYO3_USE_ABI3_FORWARD_COMPATIBILITY: 1
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - uses: astral-sh/setup-uv@v7
    - name: Install python dependencies dependencies
      run: sudo apt install -y libjpeg-dev zlib1g-dev
    - name: Install python dependencies
      run: uv sync --all-packages --group test
    - name: Install node dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Reset database
      run: uv run ./dev/db-reset.sh
    - name: Run Playwright tests
      run: npx -w @bridg/ui playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: packages/ui/playwright-report/
        retention-days: 30
  e2e-telegram-notification:
    needs: test
    if: ${{ always() }}
    uses: ./.github/workflows/telegram-notification.yml
    with:
      working_directory: "./ui"
      status_text: ${{ needs.test.result == 'success' && 'success' || 'failure' }}
      status_emoji: ${{ needs.test.result == 'success' && '✅' || '❌' }}
      stage_name: "e2e"
    secrets:
      chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
      bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
