[project]
name = "alchemy"
version = "0.1.0"
description = "BRIDG persistence using SQLAlchemy"
dependencies = [
    "sqlalchemy<3.0.0,>=2.0.45",
    "cattrs<25.0.0,>=24.1.2",
    "toolz<2.0.0,>=1.0.0"
]

[dependency-groups]
dev = [
    "mkinit>=1.2.0",
    "poethepoet>=0.39.0",
]
test = [
    "polyfactory>=3.2.0",
]

[build-system]
requires = ["uv_build>=0.8.12,<0.9.0"]
build-backend = "uv_build"

[tool.poe.tasks]
"alchemy:mkinit".sequence = [
    "mkinit --recursive --relative --nomods -i src/bridg/alchemy",
    "mkinit --recursive --relative --nomods -i src/bridg/alchemy/factory",
    "ruff check --fix",
    "ruff format"
]
"alchemy:mkinit".default_item_type = "cmd"

[tool.ruff]
extend = "../../pyproject.toml"

[tool.ruff.lint]
ignore = ["TID252"]

[tool.uv.build-backend]
module-name = "bridg.alchemy"
